// <auto-generated />
namespace Messenger_King_Courier.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MsengerKingCourier : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MsengerKingCourier));
        
        string IMigrationMetadata.Id
        {
            get { return "202007051817301_Msenger-King-Courier"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
